## YAML Template.
---
    
services:
  database:
    image: 'jacobalberty/firebird:latest'
    restart: unless-stopped
    ports:
      - "3051:3050"
    volumes:
      - /home/wolfi/fbdata:/firebird
    hostname: postbotixdb
  weather:
    build: .
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "9009:9009"
      - "8066:8066"
    environment:
      FBHOST: database
      FBPASS: fd66c53b0ce308ac509e
    hostname: postbotixweather
  weatherlog:
    image: weatherlog:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - "9080:9080"
      - "7777:7777"
    hostname: postbotixweatherlog  
    volumes:
      - /home/wolfi/weatherlog/running/log:/logs
      - /home/wolfi/weatherlog/running/config/apps:/config/apps            
    environment:
      firebird.host: database
      firebird.pass: fd66c53b0ce308ac509e
      WLP_DEBUG_SUSPEND: n
      WLP_DEBUG_ADDRESS: 7777 
      WLP_DEBUG_REMOTE: y
     
  #grafana:
  #  image:
  #ngix:
  #  image: 'docker.io/jc21/nginx-proxy-manager:latest'
  #  restart: unless-stopped
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #    - "81:81"
  #  volumes:
  #    - ./data:/data
  #    - ./letsencrypt:/etc/letsencrypt
      
