# Gradle properties

# Project version - single source of truth
projectVersion=0.2.0

# Quarkus
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.38.0
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.38.0
action.debug.args=--configure-on-demand -w -x check quarkusDev