apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weatherlog.fullname" . }}
  labels:
    {{- include "weatherlog.labels" . | nindent 4 }}
data:
  FIREBIRD_HOST: {{ .Values.firebird.host | quote }}
  FIREBIRD_PORT: {{ .Values.firebird.port | quote }}
  FIREBIRD_DATABASE: {{ .Values.firebird.database | quote }}
  FIREBIRD_USER: {{ .Values.firebird.user | quote }}
