apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weatherlog.fullname" . }}
  labels:
    {{- include "weatherlog.labels" . | nindent 4 }}
type: Opaque
data:
  FIREBIRD_PASS: {{ .Values.firebird.password | b64enc | quote }}
