apiVersion: v1
kind: ConfigMap
metadata:
  name: firebird-config
  namespace: <replace-with-namespace>
data:
  database_url: "jdbc:firebirdsql://<replace-with-host>:<replace-with-port>//<replace-with-db-path>?charSet=UTF-8"
