apiVersion: v1
kind: Secret
metadata:
  name: firebird-secret
  namespace: <replace-with-namespace>
type: Opaque
data:
  # echo -n "yourusername" | base64
  username: <replace-with-base64-encoded-username>
  # echo -n "yourpassword" | base64
  password: <replace-with-base64-encoded-password>
